name: Deploy to Sakura Server (Minimal)

on:
  workflow_dispatch:

jobs:
  minimal-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Connection First
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: sogoodsnet.sakura.ne.jp
        username: sogoodsnet
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 30s
        script: |
          echo "SSH Connection Test"
          whoami
          pwd
          echo "Home: $HOME"
          
    - name: Create Directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: sogoodsnet.sakura.ne.jp
        username: sogoodsnet
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 30s
        script: mkdir -p /home/sogoodsnet/www
        
    - name: Download index.html
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: sogoodsnet.sakura.ne.jp
        username: sogoodsnet
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 30s
        script: |
          cd /home/sogoodsnet/www
          curl -s -o index.html https://raw.githubusercontent.com/sogoodsnet/sogoods.net-www/main/index.html || fetch -q -o index.html https://raw.githubusercontent.com/sogoodsnet/sogoods.net-www/main/index.html
          
    - name: Download about.html
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: sogoodsnet.sakura.ne.jp
        username: sogoodsnet
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 30s
        script: |
          cd /home/sogoodsnet/www
          curl -s -o about.html https://raw.githubusercontent.com/sogoodsnet/sogoods.net-www/main/about.html || fetch -q -o about.html https://raw.githubusercontent.com/sogoodsnet/sogoods.net-www/main/about.html
          
    - name: Download style.css
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: sogoodsnet.sakura.ne.jp
        username: sogoodsnet
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 30s
        script: |
          cd /home/sogoodsnet/www
          curl -s -o style.css https://raw.githubusercontent.com/sogoodsnet/sogoods.net-www/main/style.css || fetch -q -o style.css https://raw.githubusercontent.com/sogoodsnet/sogoods.net-www/main/style.css
          
    - name: Set File Permissions
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: sogoodsnet.sakura.ne.jp
        username: sogoodsnet
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 30s
        script: |
          cd /home/sogoodsnet/www
          chmod 644 *.html *.css 2>/dev/null || true
          
    - name: Verify Deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: sogoodsnet.sakura.ne.jp
        username: sogoodsnet
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 30s
        script: |
          echo "📋 Deployment verification"
          cd /home/sogoodsnet/www
          ls -la
          echo "✅ Files deployed successfully"
          
    - name: Test Website
      run: |
        echo "🌐 Testing website access..."
        sleep 10
        
        # HTTPステータス確認
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://sogoodsnet.sakura.ne.jp/ 2>/dev/null || echo "000")
        echo "HTTP Status: $STATUS"
        
        if [ "$STATUS" = "200" ]; then
          echo "✅ Website is accessible!"
        else
          echo "⚠️ Website status: $STATUS"
        fi
        
    - name: Deployment Summary
      if: always()
      run: |
        echo "## 🚀 Minimal Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ job.status }}" == "success" ]; then
          echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "- **Method**: Step-by-step single commands" >> $GITHUB_STEP_SUMMARY
          echo "- **Files**: Individual file downloads" >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Status**: ❌ Failed at step-by-step deployment" >> $GITHUB_STEP_SUMMARY
        fi
        echo "- **URL**: https://sogoodsnet.sakura.ne.jp/" >> $GITHUB_STEP_SUMMARY